config/routes.rb
FileManager::Application.routes.draw do
  resources :file_containers

  resources :folders

end

app/models/file_container.rb
class FileContainer < ActiveRecord::Base
  belongs_to :folder
  attr_accessible :display_name, :s3_file, :folder_id

  has_attached_file :s3_file
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name

  has_many :file_containers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/file_containers_controller.rb
class FileContainersController < ApplicationController
  # GET /file_containers
  # GET /file_containers.json
  def index
    @file_containers = FileContainer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @file_containers }
    end
  end

  # GET /file_containers/1
  # GET /file_containers/1.json
  def show
    @file_container = FileContainer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @file_container }
    end
  end

  # GET /file_containers/new
  # GET /file_containers/new.json
  def new
    @file_container = FileContainer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @file_container }
    end
  end

  # GET /file_containers/1/edit
  def edit
    @file_container = FileContainer.find(params[:id])
  end

  # POST /file_containers
  # POST /file_containers.json
  def create
    @file_container = FileContainer.new(params[:file_container])

    respond_to do |format|
      if @file_container.save
        format.html { redirect_to @file_container, notice: 'File container was successfully created.' }
        format.json { render json: @file_container, status: :created, location: @file_container }
      else
        format.html { render action: "new" }
        format.json { render json: @file_container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /file_containers/1
  # PUT /file_containers/1.json
  def update
    @file_container = FileContainer.find(params[:id])

    respond_to do |format|
      if @file_container.update_attributes(params[:file_container])
        format.html { redirect_to @file_container, notice: 'File container was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @file_container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_containers/1
  # DELETE /file_containers/1.json
  def destroy
    @file_container = FileContainer.find(params[:id])
    @file_container.destroy

    respond_to do |format|
      format.html { redirect_to file_containers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @folders }
    end
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = Folder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/new
  # GET /folders/new.json
  def new
    @folder = Folder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @folder }
    end
  end

  # GET /folders/1/edit
  def edit
    @folder = Folder.find(params[:id])
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(params[:folder])

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render json: @folder, status: :created, location: @folder }
      else
        format.html { render action: "new" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /folders/1
  # PUT /folders/1.json
  def update
    @folder = Folder.find(params[:id])

    respond_to do |format|
      if @folder.update_attributes(params[:folder])
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to folders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_containers_helper.rb
module FileContainersHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/file_containers/_form.html.erb
<%= form_for(@file_container) do |f| %>
  <% if @file_container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_container.errors.count, "error") %> prohibited this file_container from being saved:</h2>

      <ul>
      <% @file_container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :folder_id %><br />
    <%= f.text_field :folder_id %>
  </div>
<div class="field">
  <%= f.label :s3_file %><br />
  <%= f.file_field :s3_file %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_containers/edit.html.erb
<h1>Editing file_container</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_container %> |
<%= link_to 'Back', file_containers_path %>

app/views/file_containers/index.html.erb
<h1>Listing file_containers</h1>

<table>
  <tr>
    <th>Display name</th>
    <th>Folder</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @file_containers.each do |file_container| %>
  <tr>
    <td><%= file_container.display_name %></td>
    <td><%= file_container.folder %></td>
    <td><%= link_to 'Show', file_container %></td>
    <td><%= link_to 'Edit', edit_file_container_path(file_container) %></td>
    <td><%= link_to 'Destroy', file_container, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New File container', new_file_container_path %>

app/views/file_containers/new.html.erb
<h1>New file_container</h1>

<%= render 'form' %>

<%= link_to 'Back', file_containers_path %>

app/views/file_containers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Display name:</b>
  <%= @file_container.display_name %>
</p>

<p>
  <b>Folder:</b>
  <%= @file_container.folder %>
</p>


<%= link_to 'Edit', edit_file_container_path(@file_container) %> |
<%= link_to 'Back', file_containers_path %>

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1>Listing folders</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @folders.each do |folder| %>
  <tr>
    <td><%= folder.name %></td>
    <td><%= link_to 'Show', folder %></td>
    <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
    <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @folder.name %>
</p>


<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>